#!/bin/bash
_set_bot () {
    echo "جاري تنزيل اكواد سورس "
    wget -q https://github.com/bodythoniq/bodython/archive/main.zip -O "bodython.zip"
    echo " تفريغ البيانات "
    unzip "bodython.zip"
    echo " تم التفريغ "
    echo " يتم التنظيف "
    sleep 5
    python3 setup/updater.py requirements.txt requirements.txt
    sleep 5
    cd "bodython-main"

    
    echo "    بدء تنزيل بيانات     "
    echo "

    "
    python3 -m bodython
}

_set_bot
